require('plugins')
require('telescope-config')
require("auto-pairs")
require("cmp-config")
require("lspconfig-config")
require("lspsaga-config")
require("nvim-tree-config")
require("treesitter-config")
require("dap-config")
require("surround")
require("autocmds")
require('mappings')

