return {
	-- "mfussenegger/nvim-lint",
	-- lazy = true,
	-- event = "LazyFile",
	-- opts = {
	-- 	-- Event to trigger linters
	-- 	events = { "BufWritePost", "BufReadPost", "InsertLeave" },
	-- },
	-- keys = {
	-- 	{
	-- 		"<leader>l",
	-- 		function()
	-- 			require("lint").try_lint()
	-- 		end,
	-- 	},
	-- },
	-- config = function()
	-- 	local lint = require("lint")
	--
	-- 	-- lint.linters_by_ft = {
	-- 	-- 	-- go = { "golangcilint" },
	-- 	-- 	-- lua = { "luac" },
	-- 	-- }
	-- 	vim.api.nvim_create_autocmd({ "BufWritePost" }, {
	-- 		callback = function()
	-- 			require("lint").try_lint()
	-- 		end,
	-- 	})
	-- end,
}
